mindfulness-at-the-computer/mindfulness-at-the-computer

README.md

*added description
*rearranged some content

README.md:updated

---

mc/gui/main_win.py

Updated online help URL

---

CONTRIBUTING.md

I've changed two words in the contributing.md file.

Edited two words in the contributing.md file

---

docs/manual-testing.md

I'm doing this as a first timer, trying to understand pull requests.

add link in docs/manual testing

---

downloads.html
index.html
participate.html
screenshots.html
user-guide.html

Reverts SunyataZero/mindfulness-at-the-computer#35

Revert "make site mobile-friendly"

---

downloads.html
index.html
participate.html
screenshots.html
user-guide.html

Reverts SunyataZero/mindfulness-at-the-computer#36

Revert "Revert "make site mobile-friendly""

---

docs/planning/theory-and-background.md
docs/platform-differences.md
docs/todo.txt

Few spelling errors are fixed inside the documentation.

issue#10 fixed typo inside documentation.

---

index.html

with 'inhaling and exhaling'.
This is better wording.

Replace 'in breath and out breath'

---

docs/howto/creating-a-new-release.md
docs/tech-architecture.md
mc/gui/main_window.py

Please check the changes and see if they are acceptable. Thank you!

Fixed grammatical errors wherever possible

---

docs/planning/theory-and-background.md

This change makes the sentence clearer.

Improves sentence syntax in theory-and-background.md

---

mc/gui/breathing_widget.py

fixed issue 60 on breathing_widget.py

fixed issue 60

---

participate.html

- added r in Reporting
- added n in Alternatively

Fixed spelling error - issue #10

---

mc/model.py

Return 0 when the table is empty, otherwise the program breaks

Empty table error

---

mc/gui/safe_delete_dialog.py

Creating this as a first PR as defined in  #71.
Thanks. Let me know if this works, and if it does, what does this add?

add str to argument in def

---

docs/design/design.puml

To view this plantuml diagram in PyCharm, install the PlantUML integration plugin. If you then open the file in PyCharm and go to View - Tool windows - PlantUML you will see the diagram. You can copy the images from the toolbar in PyCharm

first draft new design

---

docs/manual-testing.md
docs/platform-differences.md
docs/running-from-source.md
docs/tech-architecture.md

Hope this is helpful - my first contribution on git

Fixed various spelling and grammar issues

---

.idea/dictionaries/sunyata.xml
mc/gui/breathing_dlg.py
mc/gui/main_win.py
mc/mc_global.py
mc/model.py
varia/old_breathing_dialog

Changing the breathing interface to now using QGraphicsObject and using hover

Qgraphicsobject breathing

---

mc/model.py

Small type hint additions as requested  at #71

Added type hints to function headers at mc/model.py

---

mc/gui/breathing_phrase_list_wt.py
mc/gui/rest_action_list_wt.py
mc/gui/rest_settings_wt.py

Addresses #113 
Slight cleanup and reorder for button creation calls
Seems like button creation calls can be packed into a function to increase maintainability and reduce code duplication

Added tooltips to buttons

---

docs/project.md

Switched motiviation to motivation and changed wording to people who spend their time in front of the computer

Fixed spelling and changed wording of project.md

---

mc/gui/main_win.py

Added return value type hint to the following functions:
1.  _setup_main_container(self) 
2.  _setup_new_panel_in_main_window(main_container_hbox_l3)

added return value type hint

---

docs/howto/running-from-source.md
docs/howto/using-virtual-environment.md

This is a PR for issue: https://github.com/mindfulness-at-the-computer/mindfulness-at-the-computer/issues/63

add instructions for creating and using a virtual environment

---

.idea/dictionaries/sunyata.xml
mc/gui/main_win.py

Not sure if i used the right place to add these, please advice @mbed67 !

Added a title for the breathing and resting settings

---

mc/gui/main_win.py

Spelling error as per issue #10.
Glad to help

Fixed link to user guide

---

docs/design/theory-and-background.md

touching the water, I have also made several improvements in other files. Let me know if it's ok to push them all at once, or should I do them one @ a time.

Grammar improvement in md file

---

docs/design/user-perspective.md
docs/git-intro/git-basics.md
docs/howto/creating-a-new-release.md
docs/howto/manual-testing.md

Also made a few logos for this repo + organization, check your email, please. I wonder if I can be a part of the organization!

Changing grammar in a few md files

---

mc/db.py
mc/mc_global.py
mc/model.py

Please let me know if you see any mistakes on my additions.
Many thanks
Joe

Included function type hints

---

mc/gui/rest_action_list_wt.py

Just minor aesthetic details to keep in line with breathing list box.

Added placeholder text for rest action box

---

mc/gui/intro_dlg.py

the settings "lines" (label + spinbox)

Added some space above and below

---

mc/gui/breathing_dlg.py

Marked internal variables and methods as protected

Issue #107: Marked internal methods and variables as protected

---

mc/db.py
mc/gui/breathing_dlg.py
mc/gui/breathing_settings_wt.py
mc/gui/main_win.py
mc/model.py

Not closing on hover by default, instead

---

mc/gui/intro_dlg.py

Breathing dialog and notification now take less space

---

mc/model.py

and a minor change for "sharing"

Two breathing phrases removed

---

mc/gui/breathing_history_wt.py

Suggestions for better titles?
Your Breathing Patterns

Label added for the breathing history

---

.travis.yml

Details here: https://bugreports.qt.io/browse/QTBUG-64928

Installing a newer version of xvfb

---

.travis.yml

because of version problems for Qt or sip

Added note warning that the build might fail

---

README.md

Added short paragraph on motivation, let me know what you think.

Issue #103 - Motivation

---

mc/gui/rest_dlg.py

Highlighting mindful walking, and moving the buttons away from the rest of the design (good to do because this is meant to be used at a later time, when the user gets back from her break)

New layout for the rest dialog

---

mc/gui/main_win.py

This issue was fixed by having a single instance variable for the sound effects

Fixed issue #201

---

mc/gui/breathing_prepare.py
mc/gui/main_win.py

Added a notification to prepare the user for a breathing break

---

mc/gui/breathing_phrase_list_wt.py
mc/gui/rest_action_list_wt.py
mc/mc_global.py

Using setSpacing to increase the margins for the list items

---

mc/gui/main_win.py
mc/gui/sysinfo_dlg.py

Rewritten the "system info" dialog and added "copy to clipboard"

---

mc/db.py
mc/gui/breathing_dlg.py
mc/gui/breathing_phrase_list_wt.py
mc/gui/breathing_settings_wt.py
mc/gui/intro_dlg.py
mc/gui/main_win.py
mc/gui/rest_action_list_wt.py
mc/gui/rest_settings_wt.py
mc/mc_global.py
mc/model.py
varia/experimental_list_widget.py

Relative paths are now used for the audio. Reference: https://github.com/mindfulness-at-the-computer/mindfulness-at-the-computer/issues/221
Please note that this will drop all tables in your database

[WIP] Db update DROPS ALL TABLES

---

.gitignore
mc/gui/main_win.py
mc/model.py

The info window gives the path to the exported file, and it's also clickable.
Also the file name of the exported file now includes a time stamp

Export from the file menu now gives an info window popup

---

mc/gui/breathing_dlg.py

Updated the max time for ib and ob, and set a minimum size for the rect

---

mc/db.py
mc/gui/breathing_phrase_list_wt.py
mc/gui/breathing_settings_wt.py

Code commented out and database not changed (with the exception of making "Long" the default now) in case we want to go back
Reference: Issue #266

Short phrases removed

---

mc/gui/breathing_dlg.py
mc/mc_global.py
mc/model.py

Please note that these are separate from the min limit of the breathing box at the center of the breathing dialog

Added limits for the breathing history ib and ob lengths

---

mc/gui/breathing_dlg.py
mc/gui/intro_dlg.py

They incorporate the changes Milk Brewster suggested. Let me know if these work. If not, feel free to discard and forgive the errors.

Made some quick changes to the breathing dialogue suggestions.

---

test/test_main.py

I add a test for enable and disable feature tooltip in test main, def test toggle switch. I check if the message is equal to the message expected.

Add a test for tooltip in toggle switch enable and disable feature.

---

CONTRIBUTING.md
README.md
docs/design/OVERVIEW.md
docs/markdown.md
varia/unused_insights_cw.py

According to open issue #10, I'm fixing various typos on different .md and .py files. This is my first PR and my first contribution to a FLOSS project. Thank you for the opportunity to help!

Fixing some spelling errors

---

mc/model.py

I've updated some function headers in model.py adding type hints, trying to help with open issue #71

Adding type hints to function headers in model.py
